site_name: Sl3dyKR Site

nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
